import csv
import os
from datetime import datetime
from pathlib import Path
from dynamo_news.x_search_client import fetch_recent_posts_for_clusters
from dynamo_news.dynamo_governance import should_include_post

PROJECT_ROOT = Path(os.environ.get("DYNAMO_NEWS_ROOT", Path(__file__).resolve().parent.parent))


def load_master_index(path: str | None = None) -> list[dict]:
    if path is None:
        path = str(PROJECT_ROOT / "references" / "master_index.csv")
    if not os.path.exists(path):
        print(f"[warn] Master index not found at {path}")
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def generate_briefing(posts: list[dict]) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"# Dynamo News — {today}",
        f"**{len(posts)} high-signal posts** from X (correlated with Master Index + Dynamo Governance)\n",
    ]

    for p in posts:
        author = p.get("author", "unknown")
        url = p.get("url", "")
        summary = p.get("summary") or p.get("text", "")[:140] + "..."
        lines.append(f"**{author}**")
        lines.append(f"• {summary}")
        if url:
            lines.append(f"→ {url}")
        lines.append("")

    lines.append("—\n*Generated by Dynamo News • 4am & 1pm CST daily*")
    return "\n".join(lines)


def main():
    print("Dynamo News v2.1 starting with full governance layer...\n")

    master = load_master_index()
    print(f"Master index: {len(master)} entries loaded\n")

    raw_posts = fetch_recent_posts_for_clusters(clusters=[], days_back=1)

    for p in raw_posts:
        if "summary" not in p:
            p["summary"] = p.get("text", "")[:140] + "..."

    print("Running Dynamo Governance filter...\n")
    approved_posts = []
    for post in raw_posts:
        text = post.get("text", post.get("summary", ""))
        if should_include_post(text):
            approved_posts.append(post)
            print(f"  PASSED: {post.get('author', '?')}")
        else:
            print(f"  REJECTED by governance: {post.get('author', '?')}")

    print(f"\nGovernance complete: {len(approved_posts)}/{len(raw_posts)} posts approved\n")

    briefing = generate_briefing(approved_posts)

    out_dir = PROJECT_ROOT / "artifacts"
    out_dir.mkdir(exist_ok=True)
    filename = out_dir / f"Dynamo_News_{datetime.now().strftime('%Y-%m-%d')}.md"

    with open(filename, "w") as f:
        f.write(briefing)

    print(f"Governed briefing saved: {filename}")


if __name__ == "__main__":
    main()
