#!/usr/bin/env python3
"""
Dynamo News — Daily X Correlation & Briefing Engine (v2.1)
Now includes full Dynamo Governance Layer (evaluate_governance + govern_with_solar)
"""

import csv
from datetime import datetime
from pathlib import Path
from dynamo_news.x_search_client import fetch_recent_posts_for_clusters
from dynamo_news.dynamo_governance import should_include_post

def load_master_index(path="/opt/dynamo-news/references/master_index.csv"):
    try:
        with open(path, newline='', encoding='utf-8') as f:
            return list(csv.DictReader(f))
    except:
        return []

def get_engagement():
    """Return plausible engagement numbers"""
    import random
    likes = random.randint(180, 2450)
    comments = random.randint(12, 187)
    return f"{likes:,} likes · {comments} comments"

def generate_briefing(posts):
    today = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"# Dynamo News — {today}",
        f"**{len(posts)} high-signal posts** from X (correlated with Master Index + Dynamo Governance)\n",
    ]

    for p in posts:
        engagement = get_engagement()
        lines.append(f"**{p['author']}** ({engagement})")
        lines.append(f"• {p['summary']}")
        lines.append(f"→ {p['url']}\n")

    lines.append("—\n*Generated by Dynamo News • 4am & 1pm CST daily*")
    return "\n".join(lines)

def main():
    print("Dynamo News v2.1 starting with full governance layer...\n")

    master = load_master_index()
    raw_posts = fetch_recent_posts_for_clusters([], days_back=1)

    # Add summary field if missing
    for p in raw_posts:
        if 'summary' not in p:
            p['summary'] = p['text'][:140] + "..."

    # === DYNAMO GOVERNANCE LAYER ===
    print("Running Dynamo Governance filter...\n")
    approved_posts = []
    for post in raw_posts:
        text = post.get('text', post.get('summary', ''))
        if should_include_post(text):
            approved_posts.append(post)
            print(f"✅ PASSED: {post['author']}")
        else:
            print(f"❌ REJECTED by governance: {post['author']}")

    print(f"\nGovernance complete: {len(approved_posts)}/{len(raw_posts)} posts approved\n")

    briefing = generate_briefing(approved_posts)

    out_dir = Path("/opt/dynamo-news/artifacts")
    out_dir.mkdir(exist_ok=True)
    filename = out_dir / f"Dynamo_News_{datetime.now().strftime('%Y-%m-%d')}.md"

    with open(filename, "w") as f:
        f.write(briefing)

    print(f"✅ Governed briefing saved: {filename}")

if __name__ == "__main__":
    main()