#!/usr/bin/env python3
"""
Dynamo News Skill Runner
This is the main entry point when the skill is triggered inside Hermes.
It uses native agent tools (x_search) when available.
"""

from datetime import datetime
from pathlib import Path
from typing import List, Dict

from dynamo_news.x_search_client import fetch_recent_posts_for_clusters
from dynamo_news.dynamo_governance import evaluate_post

def run_daily_briefing() -> str:
    """
    Main function called by the Dynamo News skill.
    Fetches real posts, applies governance, and generates the report.
    """
    print("Dynamo News Skill: Starting daily briefing generation...\n")

    # 1. Fetch posts using real x_search (when running inside Hermes)
    posts = fetch_recent_posts_for_clusters(
        clusters=[
            "sovereignty OR \"local AI\" OR \"self-hosted\" OR offline OR airgap",
            "governance OR \"self-healing\" OR \"agent harness\"",
            "Polymarket OR execution OR \"real-money agents\"",
            "edge AI OR \"on-device\" OR quantization"
        ],
        days_back=1
    )

    print(f"Fetched {len(posts)} posts from X\n")

    # 2. Evaluate each post through governance
    evaluated = []
    for post in posts:
        text = post.get("text", post.get("summary", ""))
        result = evaluate_post(text)

        evaluated.append({
            "author": post.get("author"),
            "text": text[:180],
            "url": post.get("url"),
            "governance": result
        })

    # 3. Sort by governance score (isotopic ratio or confidence)
    evaluated.sort(
        key=lambda x: x["governance"].get("matrix", {}).get("confidence", 0),
        reverse=True
    )

    # 4. Generate report (top 10)
    today = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"# Dynamo News — {today}",
        f"**{len(evaluated)} posts evaluated** | Top results after Dynamo Governance\n"
    ]

    for item in evaluated[:10]:
        gov = item["governance"]
        matrix = gov.get("matrix", {})
        rec = matrix.get("recommendation", "UNKNOWN")
        conf = matrix.get("confidence", 0.0)

        lines.append(f"**{item['author']}**")
        lines.append(f"• {item['text']}")
        lines.append(f"**Governance:** {rec} (conf={conf:.2f})")
        lines.append(f"→ {item['url']}\n")

    lines.append("—")
    lines.append("*Generated by Dynamo News Skill • 4am & 1pm CST daily*")

    report = "\n".join(lines)

    # 5. Save report
    artifacts_dir = Path("/opt/dynamo-news/artifacts")
    artifacts_dir.mkdir(exist_ok=True)
    filename = artifacts_dir / f"Dynamo_News_{today}.md"

    with open(filename, "w") as f:
        f.write(report)

    print(f"Report saved to: {filename}\n")
    print("=== DAILY BRIEFING ===\n")
    print(report)
    print("\n=== END ===")

    return report


if __name__ == "__main__":
    run_daily_briefing()